name: Deploy Shopping Cart to cPanel

on:
  push:
    branches:
      - main
      - master  # Se ejecutará cada vez que subas cambios a main o master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Obtener el código
        uses: actions/checkout@v4

      - name: 🚀 Subir a cPanel por SFTP
        uses: wangyucode/sftp-upload-action@v3
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          privateKey: ${{ secrets.FTP_KEY }}
          passphrase: ${{ secrets.FTP_KEY_PASSPHRASE }}
          localDir: '.'
          remoteDir: 'public_html'
          exclude: '.git/**,.github/**'
